name: test_project


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  flutter_bloc: ^8.1.6
  get_it: ^7.2.0
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  retrofit_generator: ^8.0.6
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0

flutter:


  uses-material-design: true
